// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rncwtosijbxpbwxedshb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuY3d0b3NpamJ4cGJ3eGVkc2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDUxODksImV4cCI6MjA2NDc4MTE4OX0.QidRb3bk0M5xd5jnnUARcfW_42_W96KoeIoLH9idnvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);